Check if homebrew is installed before downloading
Aayush9029/Native-Youtube pull request #23
Opened 2021-05-25 05:45 UTC by nathom

Right now, `install.sh` will waste time trying to install Homebrew even if it is installed. I added a check for the `brew` command so that this issue is fixed. I also removed the sleep statements from the bottom because they're unnecessary.

2021-05-25 06:09 UTC, Aayush9029 commented
This is amazing, should we also check for YouTube-dl and mpv installation?

2021-05-25 06:31 UTC, insomnia-creator requested changes
Change installation types to PR #18 , just merge the checks with that. such as rm etc.

2021-05-25 06:58 UTC, insomnia-creator commented
```bash
echo "Checking /Installing"
if ! type brew > /dev/null;
then
echo "Installing Homebrew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
echo "Installing / Checking dependencies"
if brew ls --versions mpv && brew ls --versions youtube-dl > /dev/null;
then
echo "Not installing because the packages already exist"
else
echo "Installing Dependencies"
brew install mpv
brew install youtube-dl
brew link mpv
brew link youtube-dl

fi

echo "Downloading..."
cd /Applications
curl -LO https://github.com/Aayush9029/Native-Youtube/releases/download/v0.02/Muubii.app.zip

echo "Installing"
unzip -qq Muubii.app.zip
rm Muubii.app.zip

echo "Installed"

echo "Exiting terminal in 3"
sleep 1
echo "2"
sleep 1
echo "1"
sleep 1
exit
```

Update install.sh with this code, I'll update it on the DMG end.

2021-05-25 06:58 UTC, insomnia-creator commented
This checks if dependencies are installed as well

2021-05-25 07:22 UTC, insomnia-creator commented
```bash
CYAN_IS_SUS="\033[0;36m"
RED="\033[0;31m"
YELLOW="\033[0;33m"
PURPLE="\033[0;35m"
GREEN="\033[0;32m"

echo "${YELLOW}Checking / ${RED}Installing"
if ! type brew > /dev/null;
then
echo "${CYAN_IS_SUS}Installing ${GREEN}Homebrew..."
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
echo "${PURPLE}Installing / ${YELLOW}Checking dependencies"
if brew ls --versions mpv && brew ls --versions youtube-dl > /dev/null;
then
echo "${GREEN}Not installing because the packages already exist"
else
echo "${CYAN_IS_SUS}Installing Dependencies"
brew install mpv
brew install youtube-dl
brew link mpv
brew link youtube-dl

fi

echo "${YELLOW}Downloading..."
cd /Applications
curl -LO https://github.com/Aayush9029/Native-Youtube/releases/download/v0.02/Muubii.app.zip

echo "${GREEN}Installing"
unzip -qq Muubii.app.zip
rm Muubii.app.zip

echo "${PURPLE}Installed"

echo "${CYAN_IS_SUS}Exiting terminal in 3"
sleep 1
echo "${RED}2"
sleep 1
echo "${YELLOW}1"
sleep 1
exit```

Colourful version

2021-06-04 22:33 UTC, Aayush9029 commented
https://github.com/Aayush9029/Native-Youtube/pull/24

2021-06-04 22:33 UTC, closed without merging